// src/routes/search/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	import FaSolidSearch from 'svelte-icons-pack/fa/FaSolidSearch';
	import FaSolidChevronLeft from 'svelte-icons-pack/fa/FaSolidChevronLeft';
	import Icon from 'svelte-icons-pack/Icon.svelte';

	import { goto } from '$app/navigation';
	import SkeletonCard from '$lib/components/SkeletonCard.svelte';
	import { anilistRequest } from '$lib/modules/anilist';
	import { querySearchByString, queryTrending } from '$lib/modules/anilist-queries';
	import AnilistCard from '$lib/components/AnilistCard.svelte';

	let inputSearch: HTMLInputElement;

	let debounceInput = '';

	let isSearching = false;
	$: isSearching = debounceInput.length > 0;

	let timer: NodeJS.Timeout;
	// @ts-ignore
	const debounce = (e) => {
		clearTimeout(timer);
		timer = setTimeout(() => {
			debounceInput = e.target.value;
		}, 1000);
	};

	// TODO: better types for anilist data
	let trendingData = [];
	let searchData = [];

	onMount(async () => {
		inputSearch.focus();

		const res = await anilistRequest(queryTrending, {});
		if (res.error) {
			console.log('error');
		}
		trendingData = res.Page.media;
	});

	$: {
		if (isSearching) {
			async function search() {
				const res = await anilistRequest(querySearchByString, { search: debounceInput });
				if (res.error) {
					console.log('error');
				}
				searchData = res.Page.media;

				isSearching = false;
			}
			search();
		}
	}
</script>

<div class="w-full flex gap-5 p-4 max-w-2xl">
	<button
		class="btn btn-lg bg-primary-500/20 ring-primary-500/50 text-white rounded-lg"
		on:click={() => goto('/')}
	>
		<div class="h-full w-full justify-center flex">
			<Icon src={FaSolidChevronLeft} color="white" size="32" className="w-full" />
		</div>
	</button>

	<fieldset class="flex justify-center w-full text-slate-100">
		<label for="Search" class="hidden"> Search </label>
		<div class="relative w-full h-14">
			<span class="absolute inset-y-0 left-0 flex items-center pl-2 mx-1">
				<Icon src={FaSolidSearch} color="white" size="20" className="w-full" />
			</span>
			<input
				type="search"
				name="Search"
				placeholder="Search..."
				class="w-full h-full py-2 pl-10 text-base transition ease-in-out !bg-transparent border border-solid rounded-md sm:w-full focus:outline-none border-slate-600"
				autoComplete="off"
				bind:this={inputSearch}
				on:input={debounce}
			/>
		</div>
	</fieldset>
</div>

<div class="w-full py-3">
	<ul class="grid grid-cols-2 gap-x-4 gap-y-8 md:grid-cols-4 xl:gap-x-8">
		{#if !searchData.length}
			{#each trendingData as result}
				<AnilistCard {result} />
			{:else}
				{#each Array(4) as _, index (index)}
					<SkeletonCard />
				{/each}
			{/each}
		{:else}
			{#each searchData as result}
				<AnilistCard {result} />
			{:else}
				{#each Array(4) as _, index (index)}
					<SkeletonCard />
				{/each}
			{/each}
		{/if}
	</ul>
</div>

// components/Search/index.jsx
import { SearchIcon } from '@heroicons/react/solid';
import { useEffect, useRef, useState } from 'react';

import { useSearch } from '../../context/SearchContext';
import media from '../../lib/anilist-api/queries/media';
import showToast from '../../lib/showToast';
import SkeletonCard from '../SkeletonCard';
import Data from './data';

function debounce(func, timeout = 1000) {
	let timer;
	return (...args) => {
		clearTimeout(timer);
		timer = setTimeout(() => {
			func.apply(this, args);
		}, timeout);
	};
}

export default function Search() {
	const { isSearching, setIsSearching } = useSearch();

	const prevSearchQuery = useRef();
	const lastRequest = useRef(null);

	const [searchQuery, setSearchQuery] = useState('');
	const [isLoading, setIsLoading] = useState(false);
	const [anilistData, setAnilistData] = useState(null);

	const emptyArray = new Array(4).fill(0);

	async function search() {
		const data = await media({
			search: searchQuery,
		});

		data.error
			? showToast(
					'Anilist Error',
					`Status Code: ${data.error.response.status}`,
					'anilistError'
			  )
			: searchQuery === lastRequest.current &&
			  (setAnilistData(data.Page.media), setIsLoading(false));
	}

	useEffect(() => {
		setSearchQuery('');
		setAnilistData(null);
	}, []);

	useEffect(() => {
		if (!searchQuery) setAnilistData(null);

		let isSearchingLocal = isSearching;

		searchQuery.length === 0
			? (setIsSearching(false), (isSearchingLocal = false))
			: (setIsSearching(true), (isSearchingLocal = true));

		!isSearchingLocal ? setIsLoading(false) : setIsLoading(true);

		lastRequest.current = searchQuery;

		if (prevSearchQuery.current !== searchQuery) {
			if (anilistData) {
				setAnilistData(null);
			}

			const fetchData = debounce(() => search());
			searchQuery.length !== 0 && fetchData();
		}
	}, [searchQuery]);

	return (
		<>
			<fieldset className='w-full space-y-1 text-slate-100 justify-center flex'>
				<label htmlFor='Search' className='hidden'>
					Search
				</label>
				<div className='relative h-14 lg:w-1/2 w-3/4'>
					<span className='absolute inset-y-0 left-0 flex items-center pl-2 '>
						<SearchIcon className='w-5 h-5 text-slate-100' />
					</span>
					<input
						type='search'
						name='Search'
						placeholder='Search...'
						className='w-full h-full py-2 pl-10 text-base rounded-md sm:w-full text-slate-100 bg-transparent focus:text-white focus:border-blue-600 focus:outline-none border border-solid border-slate-600 transition ease-in-out'
						value={searchQuery}
						onChange={(e) => {
							e.persist();
							prevSearchQuery.current = searchQuery;
							setSearchQuery(e.target.value);
						}}
						autoComplete='off'
					/>
				</div>
			</fieldset>

			{searchQuery && (
				<div className='text-4xl font-semibold text-slate-100 my-5 flex justify-center py-3'>
					<span>Search Results</span>
				</div>
			)}
			<div className='w-full py-3'>
				<ul
					role='list'
					className='grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-4 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8'>
					{isLoading &&
						emptyArray.map((_, i) => <SkeletonCard key={i} />)}
					{!isLoading &&
						anilistData &&
						anilistData.map((item) => {
							return <Data key={item.title.romaji} data={item} />;
						})}
				</ul>
			</div>
		</>
	);
}
