// src/lib/components/SkeletonCard.svelte
<li class="relative cursor-auto animate-pulse select-none">
	<div class="bg-transparent">
		<div class="shadow-xl">
			<div class="aspect-w-2 aspect-h-3 rounded-lg bg-accent-300/50" />
		</div>
		<div class="select-none space-y-2">
			<p class="w-3/4 h-4 rounded-lg bg-accent-300/50 mt-2" />
			<div class="w-2/4 h-4 rounded-lg bg-accent-300/50" />
			<div class="w-1/4 h-4 rounded-lg bg-accent-300/50" />
		</div>
	</div>
</li>

// components/SkeletonCard/index.jsx
export default function SkeletonCard() {
	return (
		<div className='relative animate-pulse cursor-auto'>
			<div className='h-48 rounded-lg dark:bg-gray-700 aspect-w-2 aspect-h-3'></div>
			<div className='flex-1 mt-2 space-y-1'>
				<div className='w-3/4 h-4 rounded dark:bg-gray-700'></div>
				<div className='w-2/4 h-4 rounded dark:bg-gray-700'></div>
				<div className='w-1/4 h-4 rounded dark:bg-gray-700'></div>
			</div>
		</div>
	);
}
